### ISSUE TITLE
Comments on Lang.java

### ISSUE THREAD

**Issue by chrisoutwright** [CJMinecraft01/BitOfEverything#10]
Concerning the [Lang.java](https://github.com/CJMinecraft01/BitOfEverything/blob/master/src/main/java/cjminecraft/bitofeverything/util/Lang.java) file, it seems that in inventory tab, every items gets a number to its name associated. 
It maybe due to the Lang.java class. Could somebody explain exactly what it does with all those String methods? That would be great!

**Comment by Fr1me** [comment]
Is the number always 0?

**Comment by chrisoutwright** [comment]
Hello,
as seen in the picture, it is a dynamic integer.
It would be cool to know what all methods do in Lang.java, or maybe I
should again have a close look at it.


![2018-02-11](https://user-images.githubusercontent.com/27736055/36072572-e94bc00e-0f21-11e8-8878-a027cb90f40c.png)

**Comment by Fr1me** [comment]
Oh, well that number that you see to the side of the name is the ID of the item. As of now, I am unsure what the Lang.java methods do, but I will see if I can have CJMinecraft reply to you.

**Comment by chrisoutwright** [comment]
Thank you, I thought as much that it is an ID, and the showing of the ID concurred with me replicating the Lang.java part you have shown in your Youtube Channel. By the way, you did a good job at it. 
I was looking for getting into 'Minecraft Mod' programming explicitly for version 1.10.2 (the last version with which Nvidia 3D Vision patch is working to play Minecraft in 3D ;.) and I stumbled over your channel.

My goal is it to introduce  a new 'structure type' to spawn randomly with new entities like the villagers, only that the entities would not be based on existing ones, and that one could create dialogue trees with village achievements! Maybe this is too big a challenge right now ;.), also because one would have to create 3D Models and I know little about how these can be created for Minecraft in which format.

I would also be interested in AI for Mobs or villagers and more dynamic villages (decisions in one village changes specs and options for others!)

**Comment by Fr1me** [comment]
I am not the creator of this mod, but if you would like to receive more help from other people, be sure to join the creator's discord server at https://discord.gg/ZvhUKkd

**Comment by CJMinecraft01** [comment]
The Lang.java class was a class I used to be able to get a localised version of a string. I realised after the creation of the class, it could be simplified to be simple I18n.format (instead of Utils.getLang().localize())
